spring.application.name=bird-observation-project
spring.datasource.url=jdbc:postgresql://localhost:5432/birdlog
spring.datasource.username=postgres
spring.datasource.password=birdsAreCool!
spring.jpa.hibernate.ddl-auto=update